Repository nathan-v/aws_okta_keyman, pull requests merged in 2019-10, with the labels that each got.

#20 Fix typo in README.md
  README.md
Labels: bug

#21 Bazimov fix/yaml loader warning
  aws_okta_keyman/config.py
  requirements.txt
Labels: bug, code cleanup

#13 Fixes exception on invalid menu selection
  aws_okta_keyman/keyman.py
  aws_okta_keyman/test/keyman_test.py
Labels: bug

#22 Duo browserless MFA, version bump to 0.5, other fixes
  CONTRIBUTING.md
  README.md
  SECURITY.md
  aws_okta_keyman/aws.py
  aws_okta_keyman/config.py
  aws_okta_keyman/duo.py
  aws_okta_keyman/keyman.py
  aws_okta_keyman/metadata.py
  aws_okta_keyman/okta.py
  aws_okta_keyman/test/aws_test.py
  aws_okta_keyman/test/config_test.py
  aws_okta_keyman/test/duo_test.py
  aws_okta_keyman/test/keyman_test.py
  aws_okta_keyman/test/okta_test.py
  requirements.txt
  setup.py
Labels: code cleanup, enhancement

#23 Automatic AWS Accounts from Okta, Automatic Usernames, v0.5.1
  README.md
  aws_okta_keyman/config.py
  aws_okta_keyman/keyman.py
  aws_okta_keyman/metadata.py
  aws_okta_keyman/okta.py
  aws_okta_keyman/okta_saml.py
  aws_okta_keyman/test/config_test.py
  aws_okta_keyman/test/keyman_test.py
  aws_okta_keyman/test/okta_saml_test.py
  aws_okta_keyman/test/okta_test.py
  setup.py
Labels: code cleanup, enhancement
